
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.SysuserScalarFieldEnum = {
  id: 'id',
  account: 'account',
  password: 'password',
  email: 'email',
  role: 'role',
  status: 'status',
  username: 'username',
  avatarUrl: 'avatarUrl',
  phone: 'phone',
  preferredCurrency: 'preferredCurrency',
  preferredLocale: 'preferredLocale',
  countryCode: 'countryCode',
  countryName: 'countryName',
  purchaseCount: 'purchaseCount',
  adminNote: 'adminNote',
  customerType: 'customerType',
  ringSizeUs: 'ringSizeUs',
  ringSizeEu: 'ringSizeEu',
  braceletSize: 'braceletSize',
  savedPreferencesJson: 'savedPreferencesJson',
  savedSizesJson: 'savedSizesJson',
  lastLoginAt: 'lastLoginAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  parentId: 'parentId',
  level: 'level',
  name: 'name',
  slug: 'slug',
  imageUrl: 'imageUrl',
  iconUrl: 'iconUrl',
  bannerImageUrl: 'bannerImageUrl',
  description: 'description',
  seoTitle: 'seoTitle',
  seoDescription: 'seoDescription',
  seoKeywords: 'seoKeywords',
  sortWeight: 'sortWeight',
  status: 'status',
  path: 'path',
  isBrandCategory: 'isBrandCategory',
  brandCode: 'brandCode',
  brandKeywordsJson: 'brandKeywordsJson',
  homepageConfigJson: 'homepageConfigJson',
  categoryDisplayConfigJson: 'categoryDisplayConfigJson',
  keywordMappingJson: 'keywordMappingJson',
  priceCoefficient: 'priceCoefficient',
  translationsJson: 'translationsJson',
  seoTranslationsJson: 'seoTranslationsJson',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CategorynavconfigScalarFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  navTitle: 'navTitle',
  sortWeight: 'sortWeight',
  isVisible: 'isVisible',
  badgeText: 'badgeText',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  name: 'name',
  slug: 'slug',
  productCode: 'productCode',
  source: 'source',
  supplierName: 'supplierName',
  status: 'status',
  productType: 'productType',
  goodsStatus: 'goodsStatus',
  costPrice: 'costPrice',
  priceCoefficient: 'priceCoefficient',
  detailText: 'detailText',
  brandName: 'brandName',
  brandCategoryId: 'brandCategoryId',
  brandMatchKeyword: 'brandMatchKeyword',
  autoBrandMatched: 'autoBrandMatched',
  materialType: 'materialType',
  gemstoneType: 'gemstoneType',
  metalPurity: 'metalPurity',
  platingProcess: 'platingProcess',
  totalCarat: 'totalCarat',
  weightGram: 'weightGram',
  mainImageUrl: 'mainImageUrl',
  hoverImageUrl: 'hoverImageUrl',
  wearImageUrl: 'wearImageUrl',
  videoUrl: 'videoUrl',
  rotate360Json: 'rotate360Json',
  galleryJson: 'galleryJson',
  shortDescription: 'shortDescription',
  designStory: 'designStory',
  translationsJson: 'translationsJson',
  detailTranslationsJson: 'detailTranslationsJson',
  sellingPointsJson: 'sellingPointsJson',
  detailContentJson: 'detailContentJson',
  parameterJson: 'parameterJson',
  careGuideJson: 'careGuideJson',
  sizeGuideJson: 'sizeGuideJson',
  engravingPreviewBaseUrl: 'engravingPreviewBaseUrl',
  packagingImageUrl: 'packagingImageUrl',
  certificateInfo: 'certificateInfo',
  tradeInfoJson: 'tradeInfoJson',
  faqJson: 'faqJson',
  ratingAverage: 'ratingAverage',
  ratingCount: 'ratingCount',
  soldCount: 'soldCount',
  isNewArrival: 'isNewArrival',
  isBestSeller: 'isBestSeller',
  isLimitedDiscount: 'isLimitedDiscount',
  sortWeight: 'sortWeight',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductskuScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  skuCode: 'skuCode',
  imageUrl: 'imageUrl',
  minOrderQty: 'minOrderQty',
  materialType: 'materialType',
  gemstoneType: 'gemstoneType',
  ringSizeUs: 'ringSizeUs',
  ringSizeEu: 'ringSizeEu',
  materialLabel: 'materialLabel',
  sizeLabel: 'sizeLabel',
  necklaceLengthInch: 'necklaceLengthInch',
  braceletLengthCm: 'braceletLengthCm',
  engravingSupported: 'engravingSupported',
  engravingMaxChars: 'engravingMaxChars',
  fontOptionsJson: 'fontOptionsJson',
  extraFee: 'extraFee',
  price: 'price',
  originalPrice: 'originalPrice',
  stock: 'stock',
  stockStatus: 'stockStatus',
  attributeJson: 'attributeJson',
  deliveryDays: 'deliveryDays',
  weightKg: 'weightKg',
  volumeM3: 'volumeM3',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CartScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CartitemScalarFieldEnum = {
  id: 'id',
  cartId: 'cartId',
  productId: 'productId',
  productSkuId: 'productSkuId',
  quantity: 'quantity',
  engravingText: 'engravingText',
  engravingFont: 'engravingFont',
  engravingPreviewUrl: 'engravingPreviewUrl',
  giftWrapSelected: 'giftWrapSelected',
  giftWrapFee: 'giftWrapFee',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ImporttaskScalarFieldEnum = {
  id: 'id',
  creatorId: 'creatorId',
  taskName: 'taskName',
  status: 'status',
  sourceLinkCount: 'sourceLinkCount',
  successCount: 'successCount',
  failureCount: 'failureCount',
  progressPercent: 'progressPercent',
  markupRate: 'markupRate',
  defaultStatus: 'defaultStatus',
  defaultCategoryId: 'defaultCategoryId',
  queueConcurrency: 'queueConcurrency',
  rateLimitMinDelaySec: 'rateLimitMinDelaySec',
  rateLimitMaxDelaySec: 'rateLimitMaxDelaySec',
  startedAt: 'startedAt',
  finishedAt: 'finishedAt',
  lastScheduledAt: 'lastScheduledAt',
  lastRateLimitedAt: 'lastRateLimitedAt',
  stockStrategyJson: 'stockStrategyJson',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ImporttaskitemScalarFieldEnum = {
  id: 'id',
  importTaskId: 'importTaskId',
  operatorId: 'operatorId',
  sourceUrl: 'sourceUrl',
  parsedName: 'parsedName',
  parsedMainImageUrl: 'parsedMainImageUrl',
  parsedPriceMin: 'parsedPriceMin',
  parsedPriceMax: 'parsedPriceMax',
  supplierName: 'supplierName',
  mainImageUrl: 'mainImageUrl',
  costPrice: 'costPrice',
  weightGrams: 'weightGrams',
  sourceCategoryName: 'sourceCategoryName',
  targetCategoryId: 'targetCategoryId',
  coefficient: 'coefficient',
  goodsStatus: 'goodsStatus',
  minimumOrderQuantity: 'minimumOrderQuantity',
  availableStock: 'availableStock',
  cnyPriceMin: 'cnyPriceMin',
  cnyPriceMax: 'cnyPriceMax',
  usdPriceMin: 'usdPriceMin',
  usdPriceMax: 'usdPriceMax',
  productDetail: 'productDetail',
  skuSummaryText: 'skuSummaryText',
  fetchStatus: 'fetchStatus',
  publishStatus: 'publishStatus',
  retryCount: 'retryCount',
  fetchStartedAt: 'fetchStartedAt',
  fetchFinishedAt: 'fetchFinishedAt',
  publishStartedAt: 'publishStartedAt',
  publishedAt: 'publishedAt',
  specSummaryJson: 'specSummaryJson',
  previewDataJson: 'previewDataJson',
  isSelected: 'isSelected',
  isPublished: 'isPublished',
  importedProductId: 'importedProductId',
  failureReason: 'failureReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UseraddressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  recipientName: 'recipientName',
  phone: 'phone',
  countryCode: 'countryCode',
  countryName: 'countryName',
  stateName: 'stateName',
  cityName: 'cityName',
  addressLine1: 'addressLine1',
  addressLine2: 'addressLine2',
  postalCode: 'postalCode',
  isDefault: 'isDefault',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WishlistitemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId',
  status: 'status',
  shareToken: 'shareToken',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SitesettingScalarFieldEnum = {
  id: 'id',
  settingType: 'settingType',
  title: 'title',
  subtitle: 'subtitle',
  contentJson: 'contentJson',
  imageUrl: 'imageUrl',
  localeCode: 'localeCode',
  currencyCode: 'currencyCode',
  sortWeight: 'sortWeight',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LookbookScalarFieldEnum = {
  id: 'id',
  title: 'title',
  subtitle: 'subtitle',
  imageUrl: 'imageUrl',
  videoUrl: 'videoUrl',
  description: 'description',
  isActive: 'isActive',
  sortWeight: 'sortWeight',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LookbookproductScalarFieldEnum = {
  id: 'id',
  lookbookId: 'lookbookId',
  productId: 'productId',
  hotspotJson: 'hotspotJson'
};

exports.Prisma.HomeRecommendCollectionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  sourceZoneId: 'sourceZoneId',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.HomeRecommendCollectionItemScalarFieldEnum = {
  id: 'id',
  collectionId: 'collectionId',
  productId: 'productId',
  sortWeight: 'sortWeight',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.HomeRecommendZoneScalarFieldEnum = {
  id: 'id',
  title: 'title',
  zoneType: 'zoneType',
  pcCols: 'pcCols',
  mobileCols: 'mobileCols',
  pcRows: 'pcRows',
  sortWeight: 'sortWeight',
  isActive: 'isActive',
  boundCollectionId: 'boundCollectionId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.HomeRecommendZoneItemScalarFieldEnum = {
  id: 'id',
  zoneId: 'zoneId',
  entityType: 'entityType',
  productId: 'productId',
  categoryId: 'categoryId',
  sortWeight: 'sortWeight',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PromotioncampaignScalarFieldEnum = {
  id: 'id',
  name: 'name',
  promotionType: 'promotionType',
  code: 'code',
  discountPercent: 'discountPercent',
  discountAmount: 'discountAmount',
  minOrderAmount: 'minOrderAmount',
  startAt: 'startAt',
  endAt: 'endAt',
  usageLimit: 'usageLimit',
  usedCount: 'usedCount',
  contentJson: 'contentJson',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrderrecordScalarFieldEnum = {
  id: 'id',
  orderNo: 'orderNo',
  userId: 'userId',
  addressId: 'addressId',
  status: 'status',
  currencyCode: 'currencyCode',
  localeCode: 'localeCode',
  subtotalAmount: 'subtotalAmount',
  discountAmount: 'discountAmount',
  shippingAmount: 'shippingAmount',
  giftWrapAmount: 'giftWrapAmount',
  totalAmount: 'totalAmount',
  paymentMethod: 'paymentMethod',
  paymentStatus: 'paymentStatus',
  installmentInfo: 'installmentInfo',
  couponId: 'couponId',
  shipMethod: 'shipMethod',
  trackingCarrier: 'trackingCarrier',
  trackingNumber: 'trackingNumber',
  estimatedArrivalAt: 'estimatedArrivalAt',
  shippedAt: 'shippedAt',
  internalNote: 'internalNote',
  giftMessage: 'giftMessage',
  note: 'note',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrderitemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  productSkuId: 'productSkuId',
  productName: 'productName',
  skuCode: 'skuCode',
  materialLabel: 'materialLabel',
  sizeLabel: 'sizeLabel',
  engravingText: 'engravingText',
  engravingFont: 'engravingFont',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  lineAmount: 'lineAmount',
  giftWrapSelected: 'giftWrapSelected',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductreviewScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  userId: 'userId',
  orderId: 'orderId',
  rating: 'rating',
  title: 'title',
  content: 'content',
  imageUrlsJson: 'imageUrlsJson',
  hasImages: 'hasImages',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustomorderScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  userId: 'userId',
  productId: 'productId',
  productSkuId: 'productSkuId',
  promotionId: 'promotionId',
  engravingText: 'engravingText',
  engravingFont: 'engravingFont',
  engravingPreviewUrl: 'engravingPreviewUrl',
  status: 'status',
  productionNote: 'productionNote',
  shippingLabelUrl: 'shippingLabelUrl',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SizemappingScalarFieldEnum = {
  id: 'id',
  regionCode: 'regionCode',
  jewelryType: 'jewelryType',
  sourceSize: 'sourceSize',
  targetRegionCode: 'targetRegionCode',
  targetSize: 'targetSize',
  note: 'note',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustomerticketScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  contactName: 'contactName',
  email: 'email',
  channel: 'channel',
  subject: 'subject',
  content: 'content',
  status: 'status',
  replyContent: 'replyContent',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductcategoryScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  categoryId: 'categoryId',
  isPrimary: 'isPrimary',
  createdAt: 'createdAt'
};

exports.Prisma.FilterspecScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  inputType: 'inputType',
  optionJson: 'optionJson',
  translationsJson: 'translationsJson',
  sortWeight: 'sortWeight',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CategoryfilterbindingScalarFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  filterSpecId: 'filterSpecId',
  sortWeight: 'sortWeight',
  createdAt: 'createdAt'
};

exports.Prisma.SpectemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  fieldsJson: 'fieldsJson',
  translationsJson: 'translationsJson',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CategoryspectemplatebindingScalarFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  specTemplateId: 'specTemplateId',
  createdAt: 'createdAt'
};

exports.Prisma.CustomertagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  color: 'color',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustomertaglinkScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tagId: 'tagId',
  createdAt: 'createdAt'
};

exports.Prisma.CustomercommunicationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  channel: 'channel',
  content: 'content',
  operatorName: 'operatorName',
  createdAt: 'createdAt'
};

exports.Prisma.OrderlogisticssegmentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  segmentType: 'segmentType',
  carrierName: 'carrierName',
  trackingNumber: 'trackingNumber',
  statusLabel: 'statusLabel',
  estimatedArrivalAt: 'estimatedArrivalAt',
  shippedAt: 'shippedAt',
  remark: 'remark',
  timelineJson: 'timelineJson',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrderoperationlogScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  actionType: 'actionType',
  actionNote: 'actionNote',
  operatorName: 'operatorName',
  createdAt: 'createdAt'
};

exports.Prisma.ShippingtemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  countryCode: 'countryCode',
  minWeightKg: 'minWeightKg',
  maxWeightKg: 'maxWeightKg',
  minOrderAmount: 'minOrderAmount',
  maxOrderAmount: 'maxOrderAmount',
  shippingFee: 'shippingFee',
  freeShippingOver: 'freeShippingOver',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ShippingchannelScalarFieldEnum = {
  id: 'id',
  name: 'name',
  estimatedTime: 'estimatedTime',
  billingMode: 'billingMode',
  channelCoefficient: 'channelCoefficient',
  countryFeesJson: 'countryFeesJson',
  isEnabled: 'isEnabled',
  sortWeight: 'sortWeight',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CurrencysettingScalarFieldEnum = {
  id: 'id',
  currencyCode: 'currencyCode',
  currencyName: 'currencyName',
  exchangeRate: 'exchangeRate',
  isDefault: 'isDefault',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaxruleScalarFieldEnum = {
  id: 'id',
  countryCode: 'countryCode',
  countryName: 'countryName',
  taxType: 'taxType',
  taxRate: 'taxRate',
  taxNumber: 'taxNumber',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RolepermissionScalarFieldEnum = {
  id: 'id',
  roleCode: 'roleCode',
  permissionKey: 'permissionKey',
  isAllowed: 'isAllowed',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KeywordgroupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  groupType: 'groupType',
  parentGroupId: 'parentGroupId',
  sceneKey: 'sceneKey',
  sceneType: 'sceneType',
  sceneArea: 'sceneArea',
  sceneSlotKey: 'sceneSlotKey',
  sceneSlotName: 'sceneSlotName',
  floorTitle: 'floorTitle',
  floorIcon: 'floorIcon',
  floorLink: 'floorLink',
  homepageSortWeight: 'homepageSortWeight',
  showOnHomepage: 'showOnHomepage',
  sortWeight: 'sortWeight',
  isActive: 'isActive',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KeyworditemScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  parentKeywordId: 'parentKeywordId',
  keyword: 'keyword',
  normalizedKeyword: 'normalizedKeyword',
  sortWeight: 'sortWeight',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CategorykeywordlinkScalarFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  keywordGroupId: 'keywordGroupId',
  keywordItemId: 'keywordItemId',
  applyToHomepage: 'applyToHomepage',
  sortWeight: 'sortWeight',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CategorybannerScalarFieldEnum = {
  id: 'id',
  title: 'title',
  imageUrl: 'imageUrl',
  linkUrl: 'linkUrl',
  sortWeight: 'sortWeight',
  isEnabled: 'isEnabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Product_category_relationsScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  categoryId: 'categoryId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Product_keyword_relationsScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  keywordId: 'keywordId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KeywordgroupproductScalarFieldEnum = {
  id: 'id',
  keywordGroupId: 'keywordGroupId',
  productId: 'productId',
  sortWeight: 'sortWeight',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SuffixconfigScalarFieldEnum = {
  id: 'id',
  suffixName: 'suffixName',
  sortWeight: 'sortWeight',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BrandaliasScalarFieldEnum = {
  id: 'id',
  alias: 'alias',
  standardName: 'standardName',
  sortWeight: 'sortWeight',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.sysuserOrderByRelevanceFieldEnum = {
  id: 'id',
  account: 'account',
  password: 'password',
  email: 'email',
  username: 'username',
  avatarUrl: 'avatarUrl',
  phone: 'phone',
  preferredCurrency: 'preferredCurrency',
  preferredLocale: 'preferredLocale',
  countryCode: 'countryCode',
  countryName: 'countryName',
  adminNote: 'adminNote',
  customerType: 'customerType',
  ringSizeUs: 'ringSizeUs',
  ringSizeEu: 'ringSizeEu',
  braceletSize: 'braceletSize'
};

exports.Prisma.categoryOrderByRelevanceFieldEnum = {
  id: 'id',
  parentId: 'parentId',
  name: 'name',
  slug: 'slug',
  imageUrl: 'imageUrl',
  iconUrl: 'iconUrl',
  bannerImageUrl: 'bannerImageUrl',
  description: 'description',
  seoTitle: 'seoTitle',
  seoDescription: 'seoDescription',
  seoKeywords: 'seoKeywords',
  path: 'path',
  brandCode: 'brandCode'
};

exports.Prisma.categorynavconfigOrderByRelevanceFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  navTitle: 'navTitle',
  badgeText: 'badgeText'
};

exports.Prisma.productOrderByRelevanceFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  name: 'name',
  slug: 'slug',
  productCode: 'productCode',
  supplierName: 'supplierName',
  goodsStatus: 'goodsStatus',
  detailText: 'detailText',
  brandName: 'brandName',
  brandCategoryId: 'brandCategoryId',
  brandMatchKeyword: 'brandMatchKeyword',
  metalPurity: 'metalPurity',
  platingProcess: 'platingProcess',
  mainImageUrl: 'mainImageUrl',
  hoverImageUrl: 'hoverImageUrl',
  wearImageUrl: 'wearImageUrl',
  videoUrl: 'videoUrl',
  shortDescription: 'shortDescription',
  designStory: 'designStory',
  engravingPreviewBaseUrl: 'engravingPreviewBaseUrl',
  packagingImageUrl: 'packagingImageUrl',
  certificateInfo: 'certificateInfo'
};

exports.Prisma.productskuOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  skuCode: 'skuCode',
  imageUrl: 'imageUrl',
  ringSizeUs: 'ringSizeUs',
  ringSizeEu: 'ringSizeEu',
  materialLabel: 'materialLabel',
  sizeLabel: 'sizeLabel',
  necklaceLengthInch: 'necklaceLengthInch',
  braceletLengthCm: 'braceletLengthCm'
};

exports.Prisma.cartOrderByRelevanceFieldEnum = {
  id: 'id',
  accountId: 'accountId'
};

exports.Prisma.cartitemOrderByRelevanceFieldEnum = {
  id: 'id',
  cartId: 'cartId',
  productId: 'productId',
  productSkuId: 'productSkuId',
  engravingText: 'engravingText',
  engravingFont: 'engravingFont',
  engravingPreviewUrl: 'engravingPreviewUrl'
};

exports.Prisma.importtaskOrderByRelevanceFieldEnum = {
  id: 'id',
  creatorId: 'creatorId',
  taskName: 'taskName',
  defaultCategoryId: 'defaultCategoryId'
};

exports.Prisma.importtaskitemOrderByRelevanceFieldEnum = {
  id: 'id',
  importTaskId: 'importTaskId',
  operatorId: 'operatorId',
  sourceUrl: 'sourceUrl',
  parsedName: 'parsedName',
  parsedMainImageUrl: 'parsedMainImageUrl',
  supplierName: 'supplierName',
  mainImageUrl: 'mainImageUrl',
  sourceCategoryName: 'sourceCategoryName',
  targetCategoryId: 'targetCategoryId',
  productDetail: 'productDetail',
  skuSummaryText: 'skuSummaryText',
  importedProductId: 'importedProductId',
  failureReason: 'failureReason'
};

exports.Prisma.useraddressOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  recipientName: 'recipientName',
  phone: 'phone',
  countryCode: 'countryCode',
  countryName: 'countryName',
  stateName: 'stateName',
  cityName: 'cityName',
  addressLine1: 'addressLine1',
  addressLine2: 'addressLine2',
  postalCode: 'postalCode'
};

exports.Prisma.wishlistitemOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId',
  shareToken: 'shareToken'
};

exports.Prisma.sitesettingOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  subtitle: 'subtitle',
  imageUrl: 'imageUrl',
  localeCode: 'localeCode',
  currencyCode: 'currencyCode'
};

exports.Prisma.lookbookOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  subtitle: 'subtitle',
  imageUrl: 'imageUrl',
  videoUrl: 'videoUrl',
  description: 'description'
};

exports.Prisma.lookbookproductOrderByRelevanceFieldEnum = {
  id: 'id',
  lookbookId: 'lookbookId',
  productId: 'productId'
};

exports.Prisma.homeRecommendCollectionOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  sourceZoneId: 'sourceZoneId'
};

exports.Prisma.homeRecommendCollectionItemOrderByRelevanceFieldEnum = {
  id: 'id',
  collectionId: 'collectionId',
  productId: 'productId'
};

exports.Prisma.homeRecommendZoneOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  boundCollectionId: 'boundCollectionId'
};

exports.Prisma.homeRecommendZoneItemOrderByRelevanceFieldEnum = {
  id: 'id',
  zoneId: 'zoneId',
  productId: 'productId',
  categoryId: 'categoryId'
};

exports.Prisma.promotioncampaignOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code'
};

exports.Prisma.orderrecordOrderByRelevanceFieldEnum = {
  id: 'id',
  orderNo: 'orderNo',
  userId: 'userId',
  addressId: 'addressId',
  currencyCode: 'currencyCode',
  localeCode: 'localeCode',
  paymentStatus: 'paymentStatus',
  installmentInfo: 'installmentInfo',
  couponId: 'couponId',
  trackingCarrier: 'trackingCarrier',
  trackingNumber: 'trackingNumber',
  internalNote: 'internalNote',
  giftMessage: 'giftMessage',
  note: 'note'
};

exports.Prisma.orderitemOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  productSkuId: 'productSkuId',
  productName: 'productName',
  skuCode: 'skuCode',
  materialLabel: 'materialLabel',
  sizeLabel: 'sizeLabel',
  engravingText: 'engravingText',
  engravingFont: 'engravingFont'
};

exports.Prisma.productreviewOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  userId: 'userId',
  orderId: 'orderId',
  title: 'title',
  content: 'content'
};

exports.Prisma.customorderOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  userId: 'userId',
  productId: 'productId',
  productSkuId: 'productSkuId',
  promotionId: 'promotionId',
  engravingText: 'engravingText',
  engravingFont: 'engravingFont',
  engravingPreviewUrl: 'engravingPreviewUrl',
  productionNote: 'productionNote',
  shippingLabelUrl: 'shippingLabelUrl'
};

exports.Prisma.sizemappingOrderByRelevanceFieldEnum = {
  id: 'id',
  regionCode: 'regionCode',
  sourceSize: 'sourceSize',
  targetRegionCode: 'targetRegionCode',
  targetSize: 'targetSize',
  note: 'note'
};

exports.Prisma.customerticketOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  contactName: 'contactName',
  email: 'email',
  channel: 'channel',
  subject: 'subject',
  content: 'content',
  replyContent: 'replyContent'
};

exports.Prisma.productcategoryOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  categoryId: 'categoryId'
};

exports.Prisma.filterspecOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  inputType: 'inputType'
};

exports.Prisma.categoryfilterbindingOrderByRelevanceFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  filterSpecId: 'filterSpecId'
};

exports.Prisma.spectemplateOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code'
};

exports.Prisma.categoryspectemplatebindingOrderByRelevanceFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  specTemplateId: 'specTemplateId'
};

exports.Prisma.customertagOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  color: 'color',
  description: 'description'
};

exports.Prisma.customertaglinkOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  tagId: 'tagId'
};

exports.Prisma.customercommunicationOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  channel: 'channel',
  content: 'content',
  operatorName: 'operatorName'
};

exports.Prisma.orderlogisticssegmentOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  segmentType: 'segmentType',
  carrierName: 'carrierName',
  trackingNumber: 'trackingNumber',
  statusLabel: 'statusLabel',
  remark: 'remark'
};

exports.Prisma.orderoperationlogOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  actionType: 'actionType',
  actionNote: 'actionNote',
  operatorName: 'operatorName'
};

exports.Prisma.shippingtemplateOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  countryCode: 'countryCode'
};

exports.Prisma.shippingchannelOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  estimatedTime: 'estimatedTime',
  billingMode: 'billingMode'
};

exports.Prisma.currencysettingOrderByRelevanceFieldEnum = {
  id: 'id',
  currencyCode: 'currencyCode',
  currencyName: 'currencyName'
};

exports.Prisma.taxruleOrderByRelevanceFieldEnum = {
  id: 'id',
  countryCode: 'countryCode',
  countryName: 'countryName',
  taxType: 'taxType',
  taxNumber: 'taxNumber'
};

exports.Prisma.rolepermissionOrderByRelevanceFieldEnum = {
  id: 'id',
  roleCode: 'roleCode',
  permissionKey: 'permissionKey'
};

exports.Prisma.keywordgroupOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  parentGroupId: 'parentGroupId',
  sceneKey: 'sceneKey',
  sceneType: 'sceneType',
  sceneSlotKey: 'sceneSlotKey',
  sceneSlotName: 'sceneSlotName',
  floorTitle: 'floorTitle',
  floorIcon: 'floorIcon',
  floorLink: 'floorLink',
  description: 'description'
};

exports.Prisma.keyworditemOrderByRelevanceFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  parentKeywordId: 'parentKeywordId',
  keyword: 'keyword',
  normalizedKeyword: 'normalizedKeyword'
};

exports.Prisma.categorykeywordlinkOrderByRelevanceFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  keywordGroupId: 'keywordGroupId',
  keywordItemId: 'keywordItemId'
};

exports.Prisma.categorybannerOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  imageUrl: 'imageUrl',
  linkUrl: 'linkUrl'
};

exports.Prisma.product_category_relationsOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  categoryId: 'categoryId'
};

exports.Prisma.product_keyword_relationsOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  keywordId: 'keywordId'
};

exports.Prisma.keywordgroupproductOrderByRelevanceFieldEnum = {
  id: 'id',
  keywordGroupId: 'keywordGroupId',
  productId: 'productId'
};

exports.Prisma.suffixconfigOrderByRelevanceFieldEnum = {
  id: 'id',
  suffixName: 'suffixName'
};

exports.Prisma.brandaliasOrderByRelevanceFieldEnum = {
  id: 'id',
  alias: 'alias',
  standardName: 'standardName'
};
exports.userrole = exports.$Enums.userrole = {
  CUSTOMER: 'CUSTOMER',
  ADMIN: 'ADMIN',
  SUB_ADMIN: 'SUB_ADMIN'
};

exports.userstatus = exports.$Enums.userstatus = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED'
};

exports.categorystatus = exports.$Enums.categorystatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

exports.productsource = exports.$Enums.productsource = {
  MANUAL: 'MANUAL',
  IMPORT_1688: 'IMPORT_1688',
  TABLE_IMPORT: 'TABLE_IMPORT'
};

exports.productstatus = exports.$Enums.productstatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  PREORDER: 'PREORDER'
};

exports.jewelryproducttype = exports.$Enums.jewelryproducttype = {
  RING: 'RING',
  NECKLACE: 'NECKLACE',
  EARRING: 'EARRING',
  BRACELET: 'BRACELET',
  ANKLET: 'ANKLET',
  SET: 'SET',
  MENS_JEWELRY: 'MENS_JEWELRY',
  GIFT_BOX: 'GIFT_BOX',
  CUSTOM_ENGRAVING: 'CUSTOM_ENGRAVING'
};

exports.materialtype = exports.$Enums.materialtype = {
  GOLD_14K: 'GOLD_14K',
  GOLD_18K: 'GOLD_18K',
  SILVER_925: 'SILVER_925',
  GOLD_PLATED: 'GOLD_PLATED',
  ROSE_GOLD: 'ROSE_GOLD',
  WHITE_GOLD: 'WHITE_GOLD',
  PEARL: 'PEARL',
  GEMSTONE: 'GEMSTONE'
};

exports.gemstoneType = exports.$Enums.gemstoneType = {
  DIAMOND: 'DIAMOND',
  ZIRCON: 'ZIRCON',
  PEARL: 'PEARL',
  COLOR_GEM: 'COLOR_GEM',
  NONE: 'NONE'
};

exports.stockstatus = exports.$Enums.stockstatus = {
  IN_STOCK: 'IN_STOCK',
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK'
};

exports.cartitemstatus = exports.$Enums.cartitemstatus = {
  VALID: 'VALID',
  INVALID: 'INVALID'
};

exports.importtaskstatus = exports.$Enums.importtaskstatus = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  QUEUED: 'QUEUED',
  RATE_LIMITED: 'RATE_LIMITED',
  PARTIAL_SUCCESS: 'PARTIAL_SUCCESS',
  RETRY_PENDING: 'RETRY_PENDING'
};

exports.wishlistitemstatus = exports.$Enums.wishlistitemstatus = {
  ACTIVE: 'ACTIVE',
  MOVED_TO_CART: 'MOVED_TO_CART'
};

exports.sitesettingtype = exports.$Enums.sitesettingtype = {
  PROMO_BAR: 'PROMO_BAR',
  HERO_BANNER: 'HERO_BANNER',
  CATEGORY_BANNER: 'CATEGORY_BANNER',
  HOT_MATERIAL: 'HOT_MATERIAL',
  LOOKBOOK: 'LOOKBOOK',
  TRUST_BADGE: 'TRUST_BADGE',
  HOT_SEARCH: 'HOT_SEARCH',
  FOOTER_LINK: 'FOOTER_LINK',
  FLOAT_CONTACT: 'FLOAT_CONTACT',
  HOMEPAGE_POSTER: 'HOMEPAGE_POSTER',
  HOME_SECTION: 'HOME_SECTION',
  STATIC_COPY: 'STATIC_COPY',
  EMAIL_TEMPLATE: 'EMAIL_TEMPLATE',
  PAYMENT_METHOD: 'PAYMENT_METHOD',
  CURRENCY_SETTING: 'CURRENCY_SETTING',
  EXCHANGE_RATE: 'EXCHANGE_RATE',
  SHIPPING_TEMPLATE: 'SHIPPING_TEMPLATE',
  TAX_RULE: 'TAX_RULE',
  ROLE_PERMISSION: 'ROLE_PERMISSION',
  HOME_BRAND_SECTION: 'HOME_BRAND_SECTION',
  HOME_REVIEW_SECTION: 'HOME_REVIEW_SECTION',
  HOME_FEATURED_KEYWORDS: 'HOME_FEATURED_KEYWORDS',
  FRONTEND_SCENE_SLOT: 'FRONTEND_SCENE_SLOT'
};

exports.homerecommendzonetype = exports.$Enums.homerecommendzonetype = {
  PRODUCT: 'PRODUCT',
  CATEGORY: 'CATEGORY',
  SIDE_NAV: 'SIDE_NAV'
};

exports.promotiontype = exports.$Enums.promotiontype = {
  FLASH_SALE: 'FLASH_SALE',
  COUPON: 'COUPON',
  NEW_CUSTOMER: 'NEW_CUSTOMER',
  HOLIDAY: 'HOLIDAY',
  FULL_REDUCTION: 'FULL_REDUCTION',
  PERCENTAGE_DISCOUNT: 'PERCENTAGE_DISCOUNT',
  BUY_X_GET_Y: 'BUY_X_GET_Y'
};

exports.orderstatus = exports.$Enums.orderstatus = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PAID: 'PAID',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
};

exports.paymentmethodtype = exports.$Enums.paymentmethodtype = {
  PAYPAL: 'PAYPAL',
  BANK_TRANSFER: 'BANK_TRANSFER',
  STRIPE: 'STRIPE',
  CREDIT_CARD: 'CREDIT_CARD'
};

exports.ordershipmethod = exports.$Enums.ordershipmethod = {
  STANDARD: 'STANDARD',
  EXPRESS: 'EXPRESS'
};

exports.reviewstatus = exports.$Enums.reviewstatus = {
  PUBLISHED: 'PUBLISHED',
  HIDDEN: 'HIDDEN',
  PENDING: 'PENDING'
};

exports.customorderstatus = exports.$Enums.customorderstatus = {
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  IN_PRODUCTION: 'IN_PRODUCTION',
  READY_TO_SHIP: 'READY_TO_SHIP',
  SHIPPED: 'SHIPPED',
  COMPLETED: 'COMPLETED'
};

exports.ticketstatus = exports.$Enums.ticketstatus = {
  OPEN: 'OPEN',
  REPLIED: 'REPLIED',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

exports.keywordgrouptype = exports.$Enums.keywordgrouptype = {
  BRAND: 'BRAND',
  NEW_ARRIVAL: 'NEW_ARRIVAL',
  PROMOTION: 'PROMOTION',
  GENERAL: 'GENERAL'
};

exports.keywordscenearea = exports.$Enums.keywordscenearea = {
  LEFT_NAV: 'LEFT_NAV',
  RECOMMENDATION: 'RECOMMENDATION',
  BOTH: 'BOTH'
};

exports.Prisma.ModelName = {
  sysuser: 'sysuser',
  category: 'category',
  categorynavconfig: 'categorynavconfig',
  product: 'product',
  productsku: 'productsku',
  cart: 'cart',
  cartitem: 'cartitem',
  importtask: 'importtask',
  importtaskitem: 'importtaskitem',
  useraddress: 'useraddress',
  wishlistitem: 'wishlistitem',
  sitesetting: 'sitesetting',
  lookbook: 'lookbook',
  lookbookproduct: 'lookbookproduct',
  homeRecommendCollection: 'homeRecommendCollection',
  homeRecommendCollectionItem: 'homeRecommendCollectionItem',
  homeRecommendZone: 'homeRecommendZone',
  homeRecommendZoneItem: 'homeRecommendZoneItem',
  promotioncampaign: 'promotioncampaign',
  orderrecord: 'orderrecord',
  orderitem: 'orderitem',
  productreview: 'productreview',
  customorder: 'customorder',
  sizemapping: 'sizemapping',
  customerticket: 'customerticket',
  productcategory: 'productcategory',
  filterspec: 'filterspec',
  categoryfilterbinding: 'categoryfilterbinding',
  spectemplate: 'spectemplate',
  categoryspectemplatebinding: 'categoryspectemplatebinding',
  customertag: 'customertag',
  customertaglink: 'customertaglink',
  customercommunication: 'customercommunication',
  orderlogisticssegment: 'orderlogisticssegment',
  orderoperationlog: 'orderoperationlog',
  shippingtemplate: 'shippingtemplate',
  shippingchannel: 'shippingchannel',
  currencysetting: 'currencysetting',
  taxrule: 'taxrule',
  rolepermission: 'rolepermission',
  keywordgroup: 'keywordgroup',
  keyworditem: 'keyworditem',
  categorykeywordlink: 'categorykeywordlink',
  categorybanner: 'categorybanner',
  product_category_relations: 'product_category_relations',
  product_keyword_relations: 'product_keyword_relations',
  keywordgroupproduct: 'keywordgroupproduct',
  suffixconfig: 'suffixconfig',
  brandalias: 'brandalias'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
